// flow-typed signature: 61675d967f9613058013e1038d41d940
// flow-typed version: <<STUB>>/emit-file-loader_v^0.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emit-file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emit-file-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'emit-file-loader/index' {
  declare module.exports: $Exports<'emit-file-loader'>;
}
declare module 'emit-file-loader/index.js' {
  declare module.exports: $Exports<'emit-file-loader'>;
}
