// flow-typed signature: 6f09021883fd5b249c08abb7ec658aaa
// flow-typed version: <<STUB>>/threads_v^0.10.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'threads'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'threads' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'threads/dist/slave' {
  declare module.exports: any;
}

declare module 'threads/dist/slave.min' {
  declare module.exports: any;
}

declare module 'threads/dist/threads.browser.butternut' {
  declare module.exports: any;
}

declare module 'threads/dist/threads.browser' {
  declare module.exports: any;
}

declare module 'threads/dist/threads.browser.min' {
  declare module.exports: any;
}

declare module 'threads/gulpfile' {
  declare module.exports: any;
}

declare module 'threads/karma.conf' {
  declare module.exports: any;
}

declare module 'threads/lib/bundle.browser' {
  declare module.exports: any;
}

declare module 'threads/lib/config' {
  declare module.exports: any;
}

declare module 'threads/lib/defaults.browser' {
  declare module.exports: any;
}

declare module 'threads/lib/defaults' {
  declare module.exports: any;
}

declare module 'threads/lib/defaults.node' {
  declare module.exports: any;
}

declare module 'threads/lib/index' {
  declare module.exports: any;
}

declare module 'threads/lib/job' {
  declare module.exports: any;
}

declare module 'threads/lib/pool' {
  declare module.exports: any;
}

declare module 'threads/lib/worker.browser/slave-code-uri' {
  declare module.exports: any;
}

declare module 'threads/lib/worker.browser/slave-code' {
  declare module.exports: any;
}

declare module 'threads/lib/worker.browser/worker' {
  declare module.exports: any;
}

declare module 'threads/lib/worker' {
  declare module.exports: any;
}

declare module 'threads/lib/worker.node/slave' {
  declare module.exports: any;
}

declare module 'threads/lib/worker.node/worker' {
  declare module.exports: any;
}

declare module 'threads/src/bundle.browser' {
  declare module.exports: any;
}

declare module 'threads/src/config' {
  declare module.exports: any;
}

declare module 'threads/src/defaults.browser' {
  declare module.exports: any;
}

declare module 'threads/src/defaults' {
  declare module.exports: any;
}

declare module 'threads/src/defaults.node' {
  declare module.exports: any;
}

declare module 'threads/src/index' {
  declare module.exports: any;
}

declare module 'threads/src/job' {
  declare module.exports: any;
}

declare module 'threads/src/pool' {
  declare module.exports: any;
}

declare module 'threads/src/worker.browser/slave-code-uri' {
  declare module.exports: any;
}

declare module 'threads/src/worker.browser/worker' {
  declare module.exports: any;
}

declare module 'threads/src/worker' {
  declare module.exports: any;
}

declare module 'threads/src/worker.node/slave' {
  declare module.exports: any;
}

declare module 'threads/src/worker.node/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'threads/dist/slave.js' {
  declare module.exports: $Exports<'threads/dist/slave'>;
}
declare module 'threads/dist/slave.min.js' {
  declare module.exports: $Exports<'threads/dist/slave.min'>;
}
declare module 'threads/dist/threads.browser.butternut.js' {
  declare module.exports: $Exports<'threads/dist/threads.browser.butternut'>;
}
declare module 'threads/dist/threads.browser.js' {
  declare module.exports: $Exports<'threads/dist/threads.browser'>;
}
declare module 'threads/dist/threads.browser.min.js' {
  declare module.exports: $Exports<'threads/dist/threads.browser.min'>;
}
declare module 'threads/gulpfile.js' {
  declare module.exports: $Exports<'threads/gulpfile'>;
}
declare module 'threads/karma.conf.js' {
  declare module.exports: $Exports<'threads/karma.conf'>;
}
declare module 'threads/lib/bundle.browser.js' {
  declare module.exports: $Exports<'threads/lib/bundle.browser'>;
}
declare module 'threads/lib/config.js' {
  declare module.exports: $Exports<'threads/lib/config'>;
}
declare module 'threads/lib/defaults.browser.js' {
  declare module.exports: $Exports<'threads/lib/defaults.browser'>;
}
declare module 'threads/lib/defaults.js' {
  declare module.exports: $Exports<'threads/lib/defaults'>;
}
declare module 'threads/lib/defaults.node.js' {
  declare module.exports: $Exports<'threads/lib/defaults.node'>;
}
declare module 'threads/lib/index.js' {
  declare module.exports: $Exports<'threads/lib/index'>;
}
declare module 'threads/lib/job.js' {
  declare module.exports: $Exports<'threads/lib/job'>;
}
declare module 'threads/lib/pool.js' {
  declare module.exports: $Exports<'threads/lib/pool'>;
}
declare module 'threads/lib/worker.browser/slave-code-uri.js' {
  declare module.exports: $Exports<'threads/lib/worker.browser/slave-code-uri'>;
}
declare module 'threads/lib/worker.browser/slave-code.js' {
  declare module.exports: $Exports<'threads/lib/worker.browser/slave-code'>;
}
declare module 'threads/lib/worker.browser/worker.js' {
  declare module.exports: $Exports<'threads/lib/worker.browser/worker'>;
}
declare module 'threads/lib/worker.js' {
  declare module.exports: $Exports<'threads/lib/worker'>;
}
declare module 'threads/lib/worker.node/slave.js' {
  declare module.exports: $Exports<'threads/lib/worker.node/slave'>;
}
declare module 'threads/lib/worker.node/worker.js' {
  declare module.exports: $Exports<'threads/lib/worker.node/worker'>;
}
declare module 'threads/src/bundle.browser.js' {
  declare module.exports: $Exports<'threads/src/bundle.browser'>;
}
declare module 'threads/src/config.js' {
  declare module.exports: $Exports<'threads/src/config'>;
}
declare module 'threads/src/defaults.browser.js' {
  declare module.exports: $Exports<'threads/src/defaults.browser'>;
}
declare module 'threads/src/defaults.js' {
  declare module.exports: $Exports<'threads/src/defaults'>;
}
declare module 'threads/src/defaults.node.js' {
  declare module.exports: $Exports<'threads/src/defaults.node'>;
}
declare module 'threads/src/index.js' {
  declare module.exports: $Exports<'threads/src/index'>;
}
declare module 'threads/src/job.js' {
  declare module.exports: $Exports<'threads/src/job'>;
}
declare module 'threads/src/pool.js' {
  declare module.exports: $Exports<'threads/src/pool'>;
}
declare module 'threads/src/worker.browser/slave-code-uri.js' {
  declare module.exports: $Exports<'threads/src/worker.browser/slave-code-uri'>;
}
declare module 'threads/src/worker.browser/worker.js' {
  declare module.exports: $Exports<'threads/src/worker.browser/worker'>;
}
declare module 'threads/src/worker.js' {
  declare module.exports: $Exports<'threads/src/worker'>;
}
declare module 'threads/src/worker.node/slave.js' {
  declare module.exports: $Exports<'threads/src/worker.node/slave'>;
}
declare module 'threads/src/worker.node/worker.js' {
  declare module.exports: $Exports<'threads/src/worker.node/worker'>;
}
