// flow-typed signature: 833dcf02595619518b8d637711444b31
// flow-typed version: <<STUB>>/x-ray_v^2.3.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'x-ray'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'x-ray' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'x-ray/example' {
  declare module.exports: any;
}

declare module 'x-ray/lib/absolutes' {
  declare module.exports: any;
}

declare module 'x-ray/lib/adapter' {
  declare module.exports: any;
}

declare module 'x-ray/lib/params' {
  declare module.exports: any;
}

declare module 'x-ray/lib/resolve' {
  declare module.exports: any;
}

declare module 'x-ray/lib/stream' {
  declare module.exports: any;
}

declare module 'x-ray/lib/util' {
  declare module.exports: any;
}

declare module 'x-ray/lib/walk' {
  declare module.exports: any;
}

// Filename aliases
declare module 'x-ray/example.js' {
  declare module.exports: $Exports<'x-ray/example'>;
}
declare module 'x-ray/index' {
  declare module.exports: $Exports<'x-ray'>;
}
declare module 'x-ray/index.js' {
  declare module.exports: $Exports<'x-ray'>;
}
declare module 'x-ray/lib/absolutes.js' {
  declare module.exports: $Exports<'x-ray/lib/absolutes'>;
}
declare module 'x-ray/lib/adapter.js' {
  declare module.exports: $Exports<'x-ray/lib/adapter'>;
}
declare module 'x-ray/lib/params.js' {
  declare module.exports: $Exports<'x-ray/lib/params'>;
}
declare module 'x-ray/lib/resolve.js' {
  declare module.exports: $Exports<'x-ray/lib/resolve'>;
}
declare module 'x-ray/lib/stream.js' {
  declare module.exports: $Exports<'x-ray/lib/stream'>;
}
declare module 'x-ray/lib/util.js' {
  declare module.exports: $Exports<'x-ray/lib/util'>;
}
declare module 'x-ray/lib/walk.js' {
  declare module.exports: $Exports<'x-ray/lib/walk'>;
}
